server.port=8082

spring.application.name=day10

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/library}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

springdoc.swagger-ui.path=/swagger-ui.html